/* DSB AI product draft UI — optimized AI image delivery and progress feedback. */
(() => {
  'use strict';
  const $ = selector => document.querySelector(selector);
  const MAX_REFERENCE_IMAGES = 5;
  let busy = false;
  let aiReferenceUrls = [];

  function updateImageState() {
    const imageUrl = $('#f-image')?.value.trim();
    const file = $('#f-imagefile')?.files?.[0];
    const refCount = aiReferenceUrls.length;
    const base = imageUrl ? '✓ Current product image will be analysed.' : file ? '✓ Selected photo will be uploaded first, then analysed.' : 'No main product photo selected. AI can still use your notes, reference photos, and any fields already filled in.';
    $('#aiImageState').textContent = refCount ? `${base} ${refCount} AI-only reference photo${refCount === 1 ? '' : 's'} added.` : base;
  }
  function openDialog() { const d=$('#aiProductDialog'); if(!d)return; updateImageState(); $('#aiStatus').textContent=''; renderReferencePreview(); typeof d.showModal==='function'?d.showModal():d.setAttribute('open',''); setTimeout(()=>$('#aiProductNotes')?.focus(),0); }
  function closeDialog() { const d=$('#aiProductDialog'); if(!d||busy)return; typeof d.close==='function'&&d.open?d.close():d.removeAttribute('open'); }
  function value(id){ return document.getElementById(id)?.value?.trim()||''; }
  function currentProductFacts(){
    const out={}, fields={name:'f-name',namehindi:'f-nameHindi',category:'f-category',subcategory:'f-subcategory',price:'f-price',mrp:'f-mrp',costprice:'f-costprice',description:'f-description',stock:'f-stock',stockqty:'f-stockqty',brand:'f-brand',material:'f-material',packsize:'f-packsize',specifications:'f-specifications',gtin:'f-gtin',descriptionhindi:'f-descriptionhindi',sizes:'f-sizes',sizeprices:'f-sizeprices',tags:'f-tags'};
    for(const [key,id] of Object.entries(fields)){const v=value(id);if(v)out[key]=v;} if($('#f-hasSizes')?.checked)out.hasSizes=true; return out;
  }
  async function ensureImageUrl(){ let imageUrl=value('f-image'); if(imageUrl)return imageUrl; const input=$('#f-imagefile'),file=input?.files?.[0]; if(!file)return ''; if(typeof uploadFileToCloudinary!=='function')throw new Error('Image upload helper is unavailable. Upload the photo first and retry.'); $('#aiImageState').textContent='Uploading the selected photo…'; imageUrl=await uploadFileToCloudinary(file); $('#f-image').value=imageUrl; if(typeof updateImagePreview==='function')updateImagePreview(imageUrl); input.value=''; $('#uploadStatus').textContent='Photo uploaded.'; updateImageState(); return imageUrl; }
  function setBusy(on){busy=on;const b=$('#aiGenerateBtn');if(b){b.disabled=on;b.textContent=on?'Generating…':'Generate product draft';}['#aiCloseBtn','#aiRefUploadBtn','#aiRefAddUrlBtn','#aiRefClearBtn'].forEach(s=>$(s)?.toggleAttribute('disabled',on));}
  function renderReferencePreview(){const box=$('#aiReferencePreview');if(!box)return;if(!aiReferenceUrls.length)box.innerHTML='<p class="hint" style="margin:0;">No extra AI-only reference photos added.</p>';else{box.innerHTML=aiReferenceUrls.map((url,i)=>`<div class="extra-thumb"><img src="${escapeHtml(url)}" alt="Reference photo ${i+1}" loading="lazy" decoding="async"><button type="button" data-i="${i}" aria-label="Remove reference photo">✕</button></div>`).join('');box.querySelectorAll('button[data-i]').forEach(btn=>btn.addEventListener('click',()=>{aiReferenceUrls.splice(Number(btn.dataset.i),1);renderReferencePreview();updateImageState();}));}const c=$('#aiReferenceCount');if(c)c.textContent=aiReferenceUrls.length?`${aiReferenceUrls.length}/${MAX_REFERENCE_IMAGES} added`:'Optional';}
  function pushReferenceUrl(url){const cleaned=String(url||'').trim();if(!cleaned)return false;if(!/^https:\/\//i.test(cleaned))throw new Error('Reference images must use HTTPS URLs.');if(aiReferenceUrls.includes(cleaned))return false;if(aiReferenceUrls.length>=MAX_REFERENCE_IMAGES)throw new Error(`You can add up to ${MAX_REFERENCE_IMAGES} AI-only reference photos.`);aiReferenceUrls.push(cleaned);renderReferencePreview();updateImageState();return true;}
  async function uploadReferenceImage(){if(busy)return;const s=$('#aiRefStatus'),input=$('#aiRefFile'),file=input?.files?.[0];if(!file){s.className='statusline bad';s.textContent='Choose a reference photo first.';return;}const btn=$('#aiRefUploadBtn'),label=btn.textContent;btn.disabled=true;btn.textContent='Uploading…';s.className='statusline';s.textContent='Uploading reference photo…';try{if(typeof uploadFileToCloudinary!=='function')throw new Error('Image upload helper is unavailable.');const url=await uploadFileToCloudinary(file);pushReferenceUrl(url);s.className='statusline ok';s.textContent='Reference photo added for AI.';input.value='';}catch(err){s.className='statusline bad';s.textContent=err?.message||String(err);}finally{btn.disabled=false;btn.textContent=label;}}
  function addReferenceUrl(){if(busy)return;const s=$('#aiRefStatus'),input=$('#aiRefUrl');try{if(!input?.value?.trim())throw new Error('Paste a reference photo URL first.');const added=pushReferenceUrl(input.value);s.className=added?'statusline ok':'statusline';s.textContent=added?'Reference photo added for AI.':'That reference photo is already added.';input.value='';}catch(err){s.className='statusline bad';s.textContent=err?.message||String(err);}}
  function clearReferencePhotos(){if(busy)return;aiReferenceUrls=[];renderReferencePreview();updateImageState();const s=$('#aiRefStatus');if(s){s.className='statusline';s.textContent='';}}

  // Cloudinary transformations are used only for AI analysis. The original URL
  // remains in the product form/storefront, so customer-facing image quality is unchanged.
  function aiOptimizedImageUrl(url){const v=String(url||'').trim();if(!v||!/res\.cloudinary\.com/i.test(v)||!/\/upload\//.test(v))return v;if(/\/upload\/f_auto,q_auto:eco,w_1280,c_limit\//.test(v))return v;return v.replace('/upload/','/upload/f_auto,q_auto:eco,w_1280,c_limit/');}
  function aiStage(el,text){el.className='statusline';el.textContent=text;}

  async function generateDraft(){if(busy)return;const s=$('#aiStatus');setBusy(true);aiStage(s,'1/3 Preparing product information…');try{if(!API_URL||!ADMIN_KEY)throw new Error('Connect to the admin backend first.');const imageUrl=await ensureImageUrl(),referenceUrls=aiReferenceUrls.slice(),notes=$('#aiProductNotes').value.trim(),existing=currentProductFacts();if(!imageUrl&&!referenceUrls.length&&!notes&&!Object.keys(existing).length)throw new Error('Add a product photo, AI-only reference photo, a short note, or fill at least one product field first.');const aiImageUrl=aiOptimizedImageUrl(imageUrl),aiReferenceUrls=referenceUrls.map(aiOptimizedImageUrl),count=(aiImageUrl?1:0)+aiReferenceUrls.length;aiStage(s,`2/3 Analysing ${count||'no'} image${count===1?'':'s'} and generating details…`);const response=await adminFetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({key:ADMIN_KEY,action:'aiProductDraft',imageUrl:aiImageUrl,referenceUrls:aiReferenceUrls,notes,existing}),timeoutMs:75000});const data=await response.json();if(data?.error)throw new Error(data.error);if(!data?.success||!data.draft||typeof data.draft!=='object')throw new Error('AI returned an unexpected response.');if(!window.DSBAutofill?.openDraft)throw new Error('Autofill review tool is unavailable. Refresh the admin page and retry.');s.className='statusline good';s.textContent='3/3 Draft ready. Opening review…';const d=$('#aiProductDialog');typeof d?.close==='function'&&d.open?d.close():d?.removeAttribute('open');window.DSBAutofill.openDraft(data.draft,{source:'AI generated draft',warnings:Array.isArray(data.warnings)?data.warnings:[],model:data.model||''});}catch(err){s.className='statusline bad';const m=err?.message||String(err);s.textContent=/unknown action/i.test(m)?'AI backend is not deployed yet. Update Apps Script with the latest code.gs and redeploy the web app, then reconnect the admin panel.':m;}finally{setBusy(false);}}

  document.addEventListener('DOMContentLoaded',()=>{$('#aiGenerateOpenBtn')?.addEventListener('click',openDialog);$('#aiCloseBtn')?.addEventListener('click',closeDialog);$('#aiGenerateBtn')?.addEventListener('click',generateDraft);$('#aiRefUploadBtn')?.addEventListener('click',uploadReferenceImage);$('#aiRefAddUrlBtn')?.addEventListener('click',addReferenceUrl);$('#aiRefClearBtn')?.addEventListener('click',clearReferencePhotos);$('#f-image')?.addEventListener('input',updateImageState);$('#f-imagefile')?.addEventListener('change',updateImageState);$('#aiProductDialog')?.addEventListener('click',e=>{if(e.target===$('#aiProductDialog'))closeDialog();});renderReferencePreview();updateImageState();});
  window.DSBAIProductAssist=Object.freeze({resetReferencePhotos:clearReferencePhotos});
})();
