/* DSB AI product draft generation — provider-neutral and speed optimized. */
function generateAiProductDraft_(body, actor) {
  const config = aiProviderConfig_();
  rateLimit_('ai-product:' + String(actor && actor.name || 'admin'), 30, 3600);
  const imageUrl = String(body.imageUrl || '').trim();
  const referenceUrls = sanitizeAiReferenceUrls_(body.referenceUrls || []);
  const notes = String(body.notes || '').trim().slice(0, 3500);
  const existing = sanitizeAiExisting_(body.existing || {});
  if (!imageUrl && !referenceUrls.length && !notes && !Object.keys(existing).length) throw new Error('Add a product photo, AI-only reference photo, notes, or some existing product details first.');
  if (imageUrl && !/^https:\/\//i.test(imageUrl)) throw new Error('The product image must be an HTTPS URL.');
  const images = imageUrl ? [imageUrl].concat(referenceUrls) : referenceUrls.slice();
  const result = config.apiType === 'chat_completions' ? callAiChatCompletions_(config, aiProductPrompt_(notes, existing, referenceUrls.length), images) : callAiResponses_(config, aiProductPrompt_(notes, existing, referenceUrls.length), images);
  let parsed; try { parsed = JSON.parse(result.outputText); } catch (_) { throw new Error('AI generation returned invalid structured data.'); }
  const draft = cleanAiDraft_(parsed.draft || {});
  if (!Object.keys(draft).length) throw new Error('AI could not confidently fill any supported product fields. Add a little more information and try again.');
  return { success:true, draft, warnings:Array.isArray(parsed.warnings)?parsed.warnings.map(x=>String(x||'').trim()).filter(Boolean).slice(0,8):[], model:config.model, provider:config.providerLabel, apiType:config.apiType };
}
function aiProviderConfig_() {
  const apiKey=String(secret_('AI_API_KEY',secret_('OPENAI_API_KEY',''))||'').trim();
  if(!apiKey) throw new Error('AI autofill is not configured. Add AI_API_KEY (or OPENAI_API_KEY) in Apps Script > Project settings > Script properties.');
  const baseUrl=String(secret_('AI_BASE_URL','https://api.openai.com/v1')||'').trim().replace(/\/+$/,'');
  if(!/^https:\/\//i.test(baseUrl)) throw new Error('AI_BASE_URL must be an HTTPS URL.');
  const model=String(secret_('AI_MODEL',secret_('OPENAI_MODEL','gpt-5.6-luna'))||'').trim();
  if(!model) throw new Error('AI_MODEL is empty. Set a model id in Apps Script Script Properties.');
  let apiType=String(secret_('AI_API_TYPE','responses')||'').trim().toLowerCase().replace(/[ -]+/g,'_');
  if(['chat','chat_completion','chatcompletion','chat_completions'].includes(apiType)) apiType='chat_completions';
  if(['response','responses'].includes(apiType)) apiType='responses';
  if(!['responses','chat_completions'].includes(apiType)) throw new Error('AI_API_TYPE must be "responses" or "chat_completions".');
  const detailRaw=String(secret_('AI_IMAGE_DETAIL','low')||'low').trim().toLowerCase();
  const imageDetail=/^(low|high|auto)$/.test(detailRaw)?detailRaw:'low';
  const tokenRaw=Number(secret_('AI_MAX_OUTPUT_TOKENS','1400'));
  const maxOutputTokens=Number.isFinite(tokenRaw)?Math.max(700,Math.min(2200,Math.floor(tokenRaw))):1400;
  return {apiKey,baseUrl,endpoint:aiEndpoint_(baseUrl,apiType),model,apiType,providerLabel:aiProviderLabel_(baseUrl),imageDetail,maxOutputTokens};
}
function aiEndpoint_(baseUrl,apiType){return /\/(responses|chat\/completions)$/i.test(baseUrl)?baseUrl:baseUrl+(apiType==='chat_completions'?'/chat/completions':'/responses');}
function aiProviderLabel_(baseUrl){try{return String(baseUrl).replace(/^https?:\/\//i,'').split('/')[0].slice(0,100);}catch(_){return 'configured provider';}}
function aiRequestHeaders_(config){return {Authorization:'Bearer '+config.apiKey};}
function callAiResponses_(config,prompt,imageUrls){const content=[{type:'input_text',text:prompt}];imageUrls.forEach(url=>content.push({type:'input_image',detail:config.imageDetail,image_url:url}));const data=aiFetchJson_(config,{model:config.model,store:false,max_output_tokens:config.maxOutputTokens,input:[{role:'user',content}],text:{format:{type:'json_schema',name:'dsb_product_draft',strict:true,schema:aiProductSchema_()}}});const outputText=extractOpenAiOutputText_(data);if(!outputText)throw new Error('AI generation returned no product draft.');return {outputText};}
function callAiChatCompletions_(config,prompt,imageUrls){const content=[{type:'text',text:prompt+'\n\nReturn only valid JSON matching the requested product-draft schema; do not wrap it in markdown.'}];imageUrls.forEach(url=>content.push({type:'image_url',image_url:{url,detail:config.imageDetail}}));const payload={model:config.model,messages:[{role:'user',content}],max_tokens:config.maxOutputTokens,response_format:{type:'json_schema',json_schema:{name:'dsb_product_draft',strict:true,schema:aiProductSchema_()}}};const cache=CacheService.getScriptCache(),key='ai-schema:'+Utilities.base64EncodeWebSafe(config.endpoint+'|'+config.model).slice(0,120),unsupported=cache.get(key)==='unsupported';if(unsupported)delete payload.response_format;let data;try{data=aiFetchJson_(config,payload);}catch(err){const msg=String(err&&err.message||'');if(unsupported||!/response_format|json_schema|schema|unsupported|unknown parameter|invalid parameter/i.test(msg))throw err;cache.put(key,'unsupported',21600);delete payload.response_format;data=aiFetchJson_(config,payload);}const outputText=extractChatCompletionText_(data);if(!outputText)throw new Error('AI generation returned no product draft.');return {outputText:stripJsonFence_(outputText)};}
function aiFetchJson_(config,payload){const options={method:'post',contentType:'application/json',headers:aiRequestHeaders_(config),payload:JSON.stringify(payload),muteHttpExceptions:true};let response=UrlFetchApp.fetch(config.endpoint,options),status=response.getResponseCode();if([429,502,503,504].includes(status)){Utilities.sleep(450);response=UrlFetchApp.fetch(config.endpoint,options);status=response.getResponseCode();}const raw=response.getContentText();let data;try{data=JSON.parse(raw);}catch(_){throw new Error('AI provider returned an unreadable response (HTTP '+status+').');}if(status<200||status>=300){const message=aiProviderErrorMessage_(data)||('HTTP '+status);throw new Error('AI generation failed: '+message.slice(0,400));}return data;}
function aiProviderErrorMessage_(data){if(!data)return '';if(data.error&&typeof data.error.message==='string')return data.error.message;if(typeof data.message==='string')return data.message;if(data.error&&typeof data.error==='string')return data.error;return '';}
function extractChatCompletionText_(data){const choice=data&&Array.isArray(data.choices)?data.choices[0]:null,content=choice&&choice.message?choice.message.content:'';if(typeof content==='string')return content.trim();if(Array.isArray(content))return content.map(p=>p?(typeof p.text==='string'?p.text:(p.type==='text'&&typeof p.content==='string'?p.content:'')):'').join('').trim();return '';}
function stripJsonFence_(text){return String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();}
function sanitizeAiReferenceUrls_(value){const urls=Array.isArray(value)?value:[],out=[];for(let i=0;i<urls.length;i++){const url=String(urls[i]||'').trim();if(!url||!/^https:\/\//i.test(url)||out.indexOf(url)!==-1)continue;out.push(url);if(out.length>=5)break;}return out;}
function sanitizeAiExisting_(source){const allowed=['name','namehindi','category','subcategory','price','mrp','costprice','description','stock','stockqty','brand','material','packsize','specifications','gtin','descriptionhindi','sizes','sizeprices','tags','hasSizes'],out={};allowed.forEach(key=>{const value=source[key];if(value===null||value===undefined||value==='')return;if(Array.isArray(value))out[key]=value.map(x=>String(x).trim()).filter(Boolean).slice(0,30);else if(typeof value==='boolean'||typeof value==='number')out[key]=value;else out[key]=String(value).trim().slice(0,2000);});return out;}
function aiProductPrompt_(notes,existing,referenceCount){return ['Create a professional product draft for Dhatterwal Suhag Bhandar (DSB), an Indian ecommerce shop.','Use all supplied images for visually observable details. The first image is the main product photo; remaining images are supplemental references.','Use supplied notes/existing fields as authoritative facts.','Do not invent commercial facts. Price, MRP, cost price, stock quantity, GTIN, exact sizes, material, pack quantity, or brand must be null unless supplied or clearly printed.','You may infer a sensible product name, category, subcategory, visual design, concise English/Hindi descriptions, specifications and tags when supported by the evidence.','Avoid exaggerated claims, health claims, guarantees, or invented features. Hindi should be natural retail Hindi.','For bangles/chudi/kada sizes preserve values exactly, e.g. 2.4, 2.6, 2.8.','For sizeprices use a compact string like "2.4=240, 2.6=240" only when explicit.','If uncertain return null and add a useful warning.',referenceCount?'Supplemental reference photos: '+referenceCount+'.':'Supplemental reference photos: none.',notes?'User notes:\n'+notes:'User notes: none.',Object.keys(existing).length?'Existing product fields (preserve unless notes explicitly correct them):\n'+JSON.stringify(existing):'Existing product fields: none.'].join('\n\n');}
function aiNullableString_(){return {type:['string','null']};}function aiNullableNumber_(){return {type:['number','null']};}function aiNullableBoolean_(){return {type:['boolean','null']};}function aiNullableStringArray_(){return {type:['array','null'],items:{type:'string'}};}
function aiProductSchema_(){const properties={name:aiNullableString_(),namehindi:aiNullableString_(),category:aiNullableString_(),subcategory:aiNullableString_(),price:aiNullableNumber_(),mrp:aiNullableNumber_(),costprice:aiNullableNumber_(),description:aiNullableString_(),stock:aiNullableString_(),stockqty:aiNullableNumber_(),brand:aiNullableString_(),material:aiNullableString_(),packsize:aiNullableString_(),specifications:aiNullableString_(),gtin:aiNullableString_(),descriptionhindi:aiNullableString_(),sizes:aiNullableStringArray_(),hasSizes:aiNullableBoolean_(),sizeprices:aiNullableString_(),tags:aiNullableStringArray_()};return {type:'object',properties:{draft:{type:'object',properties,required:Object.keys(properties),additionalProperties:false},warnings:{type:'array',items:{type:'string'}}},required:['draft','warnings'],additionalProperties:false};}
function extractOpenAiOutputText_(data){if(typeof data.output_text==='string'&&data.output_text.trim())return data.output_text.trim();const output=Array.isArray(data.output)?data.output:[];for(let i=0;i<output.length;i++){const content=output[i]&&Array.isArray(output[i].content)?output[i].content:[];for(let j=0;j<content.length;j++){const p=content[j];if(p&&p.type==='output_text'&&typeof p.text==='string'&&p.text.trim())return p.text.trim();}}return '';}
function cleanAiDraft_(draft){const out={},stringFields=['name','namehindi','category','subcategory','description','stock','brand','material','packsize','specifications','gtin','descriptionhindi','sizeprices'];stringFields.forEach(key=>{if(typeof draft[key]!=='string')return;const v=draft[key].trim();if(v)out[key]=v.slice(0,['description','descriptionhindi','specifications'].includes(key)?2000:1000);});['price','mrp','costprice'].forEach(key=>{const n=Number(draft[key]);if(Number.isFinite(n)&&n>=0)out[key]=n;});if(draft.stockqty!==null&&draft.stockqty!==undefined&&Number.isFinite(Number(draft.stockqty))&&Number(draft.stockqty)>=0)out.stockqty=Math.floor(Number(draft.stockqty));if(typeof draft.hasSizes==='boolean')out.hasSizes=draft.hasSizes;['sizes','tags'].forEach(key=>{if(!Array.isArray(draft[key]))return;const values=[...new Set(draft[key].map(x=>String(x||'').trim()).filter(Boolean))].slice(0,30);if(values.length)out[key]=values;});if(out.stock&&!/^(in stock|out of stock)$/i.test(out.stock))delete out.stock;return out;}
