import assert from 'node:assert/strict';
import fs from 'node:fs';
const read = f => fs.readFileSync(f, 'utf8');
const config = read('src/backend/config.gs');
const requests = read('src/backend/order-requests.gs');
const orders = read('src/backend/orders.gs');
const http = read('src/backend/http.gs');
const auth = read('src/backend/admin-auth.gs');
const cart = read('cart-ui-core.js');
const admin = read('admin.js');
const style = read('src/styles/level3-commerce.css');
assert(config.includes('ORDER_REQUESTS_SHEET') && config.includes('ORDER_STATUS_TRANSITIONS'), 'Level 3 backend config missing');
assert(requests.includes('submitOrderRequest_') && requests.includes('resolveOrderRequest_'), 'Order request lifecycle missing');
assert(requests.includes("ORDER_REQUEST_TYPES.indexOf(type)") && requests.includes("canCustomerRequestCancellation_"), 'Customer request validation missing');
assert(requests.includes('phoneHash') && !requests.includes("sheet.appendRow([sheetText_(requestId), now, sheetText_(orderId), sheetText_(type), sheetText_(message), 'Pending', '', now, sheetText_(phone)"), 'OrderRequests must not duplicate raw phone');
assert(http.includes("body.action === 'trackOrder'") && http.includes("body.action === 'submitOrderRequest'"), 'Public POST routes missing');
assert(cart.includes("action: 'trackOrder'") && !cart.includes('?action=trackOrder&orderId='), 'Tracking should not put phone/order credentials in URL');
assert(cart.includes("action: 'submitOrderRequest'") && cart.includes('Request cancellation'), 'Customer request UI missing');
assert(orders.includes("Invalid status transition from") && orders.includes('orderRequestsByOrderIds_'), 'Order lifecycle/request admin feed missing');
assert(auth.includes("'resolveOrderRequest'") && auth.includes('version: 15'), 'Admin request action/version missing');
assert(admin.includes('ORDER_STATUS_TRANSITIONS_CLIENT') && admin.includes('orderRequestsHtml') && admin.includes('resolveOrderRequest'), 'Admin Level 3 controls missing');
assert(style.includes('.track-request-panel') && style.includes('.order-request-box'), 'Level 3 styles missing');
console.log('PASS: Level 3 tracking privacy, support/cancellation requests, admin handling and status lifecycle.');
